---
# - name: Add required modules
#   modprobe:
#     name: "{{ item.name }}"
#     state: present
#   loop:
#     "{{ _module }}"
#   tags: rke2-server

# - name: Setup required sysctl params
#   sysctl:
#     name: "{{ item.key }}"
#     value: "{{ item.value }}"
#     sysctl_set: yes
#     state: present
#     reload: yes
#   loop:
#     "{{ _sysctl }}"
#   tags: rke2-server

# - name: Install packages that allow apt to be used over HTTPS
#   apt:
#     name: "{{ packages }}"
#     state: present
#     update_cache: yes
#   vars:
#     packages:
#     - apt-transport-https
#     - ca-certificates
#     - curl
#     - gnupg2
#     - software-properties-common
#   tags: rke2-server

# - name: copy templates
#   template:
#     dest: "{{ item.dest }}"
#     src: "{{ item.src | default('./templates' + item.dest + '.j2') }}"
#     owner: "{{ item.owner | default('root') }}"
#     group: "{{ item.group | default('root') }}"
#     mode: "{{ item.mode | default('0644') }}"
#   loop:
#     - { dest: "/etc/apt/sources.list" }
#   tags: rke2-server

# - name: Add signing keys
#   apt_key:
#     url: "{{ item.gpg }}"
#     state: present
#   loop: "{{ _key }}"
#   register: result
#   until: result is succeeded
#   tags: rke2-server

# - name: Add repositoies
#   apt_repository:
#     repo: "{{ item.repo }}"
#     state: present
#   loop: "{{ _repo }}"
#   register: result
#   until: result is succeeded
#   tags: rke2-server

# - name: Update all packages
#   apt:
#     name: '*'
#     state: latest
#     update_cache: yes
#   changed_when: false
#   ignore_errors: true
#   tags: rke2-server

# - name: Install packages
#   apt:
#     name: "{{ item.name }}"
#     state: "{{ item.state }}"
#   loop: "{{ _package }}"
#   register: result
#   until: result is succeeded
#   tags: rke2-server

# - name: just force systemd to reread configs
#   systemd:
#     daemon_reload: yes
#   tags: rke2-server

# - name: Start and enable services
#   systemd:
#     name: "{{ item.name }}"
#     state: started
#     enabled: yes
#     daemon_reload: yes
#   loop: "{{ _service }}"
#   register: result
#   until: result is succeeded
#   tags: rke2-server

# - name: Add /usr/local/bin to sudo secure_path
#   lineinfile:
#     line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
#     regexp: "Defaults(\s)*secure_path(\s)*="
#     state: present
#     insertafter: EOF
#     path: /etc/sudoers
#     validate: 'visudo -cf %s'
#   tags: rke2-server

- name: Download script
  get_url:
    url: "{{ item.url }}"
    # checksum: "{{ item.checksum }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  loop: "{{ _install_script }}"
  register: result
  until: result is succeeded
  tags: rke2-server

- name: Execute script
  shell: "{{ item.dest }}"
  become: true
  loop: "{{ _install_script }}"
  register: result
  until: result is succeeded
  tags: rke2-server

- name: Remove script
  file:
    path: "{{ item.dest }}"
    state: absent
  loop: "{{ _install_script }}"
  register: result
  until: result is succeeded
  tags: rke2-server

- name: Start and enable services
  systemd:
    name: "{{ item.name }}"
    state: started
    enabled: yes
    daemon_reload: yes
  loop: "{{ _service }}"
  register: result
  until: result is succeeded
  tags: rke2-server

- name: Wait until node token is generated
  wait_for:
    path: /var/lib/rancher/rke2/server/node-token
  run_once: true
  tags: rke2-server

- name: Get node token
  slurp:
    src: /var/lib/rancher/rke2/server/node-token
  register: RKE2_TOKEN
  run_once: true
  tags: rke2-server

- name: Clean up node token contents
  set_fact: 
    RKE2_TOKEN: "{{ RKE2_TOKEN['content'] | b64decode | replace('\n', '')}}"
    cacheable: yes
  run_once: yes
  tags: rke2-server

- name: Print cluster node token
  debug:
    msg: "{{ RKE2_TOKEN }}"
  tags: rke2-server

- name: Set server address
  register: RKE2_URL
  set_fact:
    RKE2_URL: "https://{{ ansible_host }}:9345"
    cacheable: yes
  run_once: yes
  tags: rke2-server

- name: Print server address
  debug:
    msg: "{{ RKE2_URL }}"
  tags: rke2-server

- name: copy the output to a local file
  copy:
    content: "{{ RKE2_TOKEN }}"
    dest: "{{ server.token_path }}"
  delegate_to: localhost
  tags: rke2-server

- name: copy the output to a local file
  copy:
    content: "{{ RKE2_URL }}"
    dest: "{{ server.url_path }}"
  delegate_to: localhost
  tags: rke2-server

- name: Create directory .kube
  file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: "u=rwx,g=rx,o="
  tags: rke2-server

- name: Copy config file to user home directory
  copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: "u=rw,g=,o="
  tags: rke2-server

- name: Replace https://localhost:6443 by https://master-ip:6443
  replace:
    path: ~{{ ansible_user }}/.kube/config
    regexp: '127.0.0.1'
    replace: "{{ ansible_host }}"
  tags: rke2-server

- name: Fetch config file to user home directory
  fetch:
    src: ~{{ ansible_user }}/.kube/config
    dest: "{{ deployment_host.kube_config }}"
    flat: yes
  tags: rke2-server