---
- name: Print cluster node token
  debug:
    msg: "{{ RKE2_TOKEN }}"
  tags: rke2-agent

- name: Print server address
  debug:
    msg: "{{ RKE2_URL }}"
  tags: rke2-agent

- name: ensure a directory exists
  file:
    path: /etc/rancher/rke2
    state: directory
  tags: rke2-agent

- name: set rke2 server config
  template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
  tags: rke2-agent

- name: Download script
  get_url:
    url: "{{ item.url }}"
    # checksum: "{{ item.checksum }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  loop: "{{ _install_script }}"
  register: result
  until: result is succeeded
  tags: rke2-agent

- name: Execute script
  shell: "INSTALL_RKE2_TYPE=agent sh {{ item.dest }}"
  become: true
  loop: "{{ _install_script }}"
  register: result
  until: result is succeeded
  tags: rke2-agent

- name: Remove script
  file:
    path: "{{ item.dest }}"
    state: absent
  loop: "{{ _install_script }}"
  register: result
  until: result is succeeded
  tags: rke2-agent

- name: Start and enable services
  systemd:
    name: "{{ item.name }}"
    state: started
    enabled: yes
    daemon_reload: yes
  loop: "{{ _service }}"
  register: result
  until: result is succeeded
  tags: rke2-agent
