---
- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
  tags: firewalld

- name: Update all packages
  apt:
    name: '*'
    state: latest
    update_cache: yes
  changed_when: false
  ignore_errors: true
  tags: firewalld

- name: Install packages
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ _package }}"
  register: result
  until: result is succeeded
  tags: firewalld

- name: Start and enable services
  systemd:
    name: "{{ item.name }}"
    state: started
    enabled: yes
    daemon_reload: yes
  loop: "{{ _service }}"
  register: result
  until: result is succeeded
  tags: firewalld

- name: Configure firewalld on master nodes
  firewalld:
    port: "{{ item.port }}/{{ item.protocol }}"
    permanent: yes
    state: enabled
  loop: '{{ _k8s_master_ports }}'
  tags: firewalld

- name: Configure firewalld on worker nodes
  firewalld:
    port: "{{ item.port }}/{{ item.protocol }}"
    permanent: yes
    state: enabled
  loop: '{{ _k8s_worker_ports }}'
  # when: "'worker' in ansible_hostname"
  tags: firewalld

- name: Reload firewalld
  shell: firewall-cmd --reload
  tags: firewalld
